services:

  backend:
    build:
      context: ./wandr-backend
    container_name: wandr-backend
    environment:
      DB_HOST: db
      DB_NAME: wandrdb
      DB_USER: wandruser
      DB_PASSWORD: wandrpassword
      JWT_SECRET: wandrprojectefreiosdev
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    container_name: wandr-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgis/postgis:16-3.4
    container_name: wandr-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: wandrdb
      POSTGRES_USER: wandruser
      POSTGRES_PASSWORD: wandrpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: